### PR TITLE
Fix gov cloud region mapping

### PR DESCRIPTION
**Pull request by dominikschubert**
## Changes Introduced

```bash
docker run -p 4567:4567 -p 4568:4568 --env AWS_REGION=us-gov-east-1 ghcr.io/etspaceman/kinesis-mock:0.2
```
Previously failed because there was no mapping for `us-gov-east-1` regions.

It also seems like there was a mixup between gov east/west which should be fixed now.

Note there might still be an issue here that needs to be fixed because gov cloud uses the "aws-gov" partition instead of "aws" in ARNs.

https://github.com/etspaceman/kinesis-mock/blob/d60ebb89acca9c78bf5a0d31df796551434477e1/src/main/scala/kinesis/mock/models/StreamArn.scala#L15 

## Checklist (check all that apply)

- [x] This change maintains backwards compatibility
- [ ] ~~I have introduced tests for all new features and changes~~ => haven't managed to get the environment to run locally yet
- [ ] ~~I have added documentation covering all new features and changes~~
- [x] This pull-request is ready for review

### CODE REVIEW

**Comment by etspaceman** [comment]
Thanks for the report and the fix! Looking into the ARN issue that you are stating.

**Comment by etspaceman** [comment]
I made a push to this branch to make the `aws-gov` arn changes that you identified.

**Comment by etspaceman** [comment]
@Mergifyio update

**Comment by dominikschubert** [comment]
> Thanks for the report and the fix! Looking into the ARN issue that you are stating.

To extend on this: We're currently also evaluating if we should tackle this in localstack. It's mostly about `aws` vs. `aws-us-gov`, but there's also `aws-cn` for example. Sorry for the misinformation before, the alternative is the full `arn:aws-us-gov:...` or the public AWS cloud one: `arn:aws:...`

Reference: https://docs.aws.amazon.com/govcloud-us/latest/UserGuide/using-govcloud-arns.html

**Comment by etspaceman** [comment]
WRT `aws-cn`, that would need to be applied to these lines?

https://github.com/etspaceman/kinesis-mock/blob/main/src/main/scala/kinesis/mock/models/AwsRegion.scala#L35-L36

**Comment by dominikschubert** [comment]
`aws-cn` should be these ones: https://github.com/etspaceman/kinesis-mock/blob/main/src/main/scala/kinesis/mock/models/AwsRegion.scala#L32-L33

This is AFAIK the full mapping:

```
{
  "aws": [
    "af-south-1",
    "ap-east-1",
    "ap-northeast-1",
    "ap-northeast-2",
    "ap-northeast-3",
    "ap-south-1",
    "ap-southeast-1",
    "ap-southeast-2",
    "ca-central-1",
    "eu-central-1",
    "eu-north-1",
    "eu-south-1",
    "eu-west-1",
    "eu-west-2",
    "eu-west-3",
    "me-south-1",
    "sa-east-1",
    "us-east-1",
    "us-east-2",
    "us-west-1",
    "us-west-2"
  ],
  "aws-cn": [
    "cn-north-1",
    "cn-northwest-1"
  ],
  "aws-us-gov": [
    "us-gov-east-1",
    "us-gov-west-1"
  ],
  "aws-iso": [
    "us-iso-east-1",
    "us-iso-west-1"
  ],
  "aws-iso-b": [
    "us-isob-east-1"
  ]
}
```

**Comment by etspaceman** [comment]
@dominikschubert updated. Can you confirm the mappings?

**Comment by dominikschubert** [comment]
> @dominikschubert updated. Can you confirm the mappings?

looks good :+1:

**Comment by etspaceman** [comment]
@Mergifyio update

**Pull request merged**
